trigger: none
stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: VMDeploy
    displayName: Deploy to VM job
    environment: arjunenv.vg1
    strategy:
      rolling:
        maxBatchSize: 2
        deploy:
          steps:
            - script: echo Hello, world! This is deploy job
              displayName: 'Run a one-line script'